### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by brbsix**
Hey, thanks for writing this. I've been looking for a good command-line Speedtest client for quite a while and really appreciate this. In case you're interested, I've made some changes. Support for Python 3, basic testing via Travis CI, argument parsing via argparse, `README.rst` instead of `README.md` so PyPI presents it correctly, have setuptools handle the entry_point scripts, use logging module for logging, make everything PEP8 compliant to keep pylint happy. Feel free to use any of it if you're interested.

### CODE REVIEW

**Comment by fopina** [comment]
Awesome, thank you!
I'll definitely pull this in a couple of days

**Comment by fopina** [comment]
It seems you removed the "bin" script (to make it easier for CLI usage). Any reason I'm missing?

**Comment by brbsix** [comment]
Yep, I removed the bin script in favor of:

```
entry_points={
    'console_scripts': ['pyspeedtest=pyspeedtest:main']
},
```

Basically this instructs setuptools to create a launcher script upon installation. See https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation for more information. You can go ahead and install the fork in a virtualenv to verify.

**Comment by fopina** [comment]
Really nice yet simple test script, I was missing travis in this repo and postponing its tests

Two small questions before I close the PR:
- why did you remove the defaults on the class methods? anything related to py3?
- usually I like to use the xrange generator instead of the range one (though apparently I didn't here!), but in py3 range is already a generator. Any hint on how would I go about supporting py3 and py2 but still using generator in both? Something other than `if py2 xrange, else range`

Thanks

**Comment by fopina** [comment]
I looked up a bit about using `range` as `xrange` in py2 and it seems it would have to rely in installing `future` or some simple hack such as

```
try:
    xrange
    range = xrange
except:
    pass
```

Both seem unnecessary in this case anyway.

Merged and submitted.

Thanks once again

**Comment by brbsix** [comment]
Sorry for the delay. If I recall correctly, I removed the class defaults just to keep the defaults defined in only one place (in this case it was with the parser). Though I wasn't really thinking about using the class directly so in that case it makes sense to put the class defaults back or maybe have both the class and parser source the defaults from a global config class. Nothing to do with Python 3 support... Anyways glad to see you were able to make use of it.

**Pull request merged**
