### PR TITLE
Added returned values and default inputs to perform_speedtest so as …

### PR DESCRIPTION
**Pull request by GadgetSteve**
…to be able to use it from other code, some restructuring and the majority of pylint reports sorted out.  I think that this makes pyspeedtest more useful as it can be called from code that is monitoring the results and posting them on-line or generating problem reports for example.

This version on the code allows perform_speedtest to be called without the opts parameter in which case it will behave the same as the command line without parameters. It now returns the stats dictionary for use by other code.

Also ran pylint on the code and addressed the majority of the issues flagged.

### CODE REVIEW

**Comment by sirgrigio** [comment]
> ...to be able to use it from other code, some restructuring and the majority of pylint reports sorted out. I think that this makes pyspeedtest more useful as it can be called from code that is monitoring the results and posting them on-line or generating problem reports for example.

Yep this is exactly the idea I had in mind and what I was trying to achieve. 
However I think there are at least a couple of downsides in your implementation:
1. Since you are building a dictionary to return it in the `perform_speedtest` function you are losing the capability of showing the output live to the user if he goes for the `default` output format;
2. I think it is better to explode the opts object once it is passed to the `perform_speedtest` function so that it would be easier to be documented and understood, e.g. something like `perform_speedtest(mode=7, format='default', ...)`

Anyway this is just my opinion, let's see what @fopina thinks :)

**Comment by GadgetSteve** [comment]
@zmcode - If you test you will find that it still displays, the results exactly the same, for the 'default' option. They are just always built into a dictionary then displayed from it by default which simplified the code quite a bit. I agree that your point 2 would be a good one though.  Thanks for the kind words.

**Comment by sirgrigio** [comment]
> If you test you will find that it still displays, the results exactly the same, for the 'default' option. 

@GadgetSteve - Yeah but it first has to calculate them all whereas right now it prints them step by step without having to wait for the all process to complete. We can argue that this is not necessary but I personally think it is better to show them as soon as they are calculated if the user chooses the `default` format.

**Comment by GadgetSteve** [comment]
Some changes to allow progress to be displayed as work goes on as per @zmcode comments.

**Comment by fopina** [comment]
Actually, I made this originally to be called from other modules, not to be called from the command line. Command line was only a build-up from there :)

That's why I'm not sure I understand the purpose of making `perform_speedtest()` callable from other modules.
Other modules should do exactly what `perform_speedtest()` does, which is create a `SpeedTest()` object and then call `download()`, `upload()`, `ping()` whenever and as many times as they want and however they feel like..

**Comment by sirgrigio** [comment]
> ...which is create a SpeedTest() object and then call download(), upload(), ping() whenever and as many times as they want and however they feel like..

@fopina - That's exactly why I like this script more than others out there.

> That's why I'm not sure I understand the purpose of making perform_speedtest() callable from other modules.

@fopina @GadgetSteve - For me the purpose of `perform_speedtest` is just to logically separate the args parsing that is done in the `main` function from the actual speedtest and, since we have a command line, it seemed to me a good idea to introduce some more useful output formats. 

My next step would be only to explode the opts object taken by `perform_speedtest` into single objects and document it so that also other calling modules can take advantage of it if they just need a "default" behaviour.

**Comment by GadgetSteve** [comment]
@zmcode - If only there had been some docstrings &/or usage detail on the web page that mentioned of the idea of creating SpeedTest then calling the required functions then I wouldn't have found at least one script which is actually being held up as an example of what you can do with python that calls pyspeedtest in a shell and captures the output and then uses re to get the data.

**Comment by fopina** [comment]
I was definitely merging the docstrings, really useful (and badly forgotten) :D
Just wondering about the perform_speedtest.
The initial version was mainly that: class to be used for other modules and a simple **main** just for fun.

But yes, pyspeedtest wasn't in pip 4 years ago and I didn't really work on the README, and indeed I must :D

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(

**Pull request closed without merging**
